const utilities: { [key:string]: string[]} = {
  animation: [
    'animate-${static}',
  ],
  backdropBlur: [
    'backdrop-blur-${static}',
    'backdrop-blur-[11px]',
  ],
  backdropBrightness: [
    'backdrop-brightness-${static}',
    'backdrop-brightness-[1.23]',
  ],
  backdropContrast: [
    'backdrop-contrast-${static}',
    'backdrop-contrast-[0.87]',
  ],
  backdropGrayscale: [
    'backdrop-grayscale-${static}',
    'backdrop-grayscale-[0.42]',
  ],
  backdropHueRotate: [
    'backdrop-hue-rotate-${static}',
    'backdrop-hue-rotate-[1.57rad]',
  ],
  backdropInvert: [
    'backdrop-invert-${static}',
    'backdrop-invert-[0.66]',
  ],
  backdropOpacity: [
    'backdrop-opacity-${static}',
    'backdrop-opacity-[22%]',
  ],
  backdropSaturate: [
    'backdrop-saturate-${static}',
    'backdrop-saturate-[144%]',
  ],
  backdropSepia: [
    'backdrop-sepia-${static}',
    'backdrop-sepia-[0.38]',
  ],
  backgroundColor: [
    'bg-${color}',
    'bg-[#0f0]',
    'bg-[#ff0000]',
    'bg-[#0000ffcc]',
    'bg-[rgb(123,123,123)]',
    'bg-[rgba(123,123,123,0.5)]',
    'bg-[hsl(0,100%,50%)]',
    'bg-[hsla(0,100%,50%,0.3)]',
  ],
  backgroundImage: [
    'bg-${static}',
  ],
  backgroundOpacity: [
    'bg-opacity-${static}',
    'bg-opacity-${int<=100}',
    'bg-opacity-[0.11]',
    'bg-opacity-[var(--value)]',
  ],
  backgroundPosition: [
    'bg-${static}',
  ],
  backgroundSize: [
    'bg-${static}',
  ],
  blur: [
    'blur-${static}',
    'blur-${int}',
    'blur-${size}',
    'blur-[15px]',
  ],
  borderColor: [
    'border-${color}',
    'border-[#f00]',
  ],
  borderOpacity: [
    'border-opacity-${static}',
    'border-opacity-${int<=100}',
  ],
  borderRadius: [
    'rounded-${static}',
    'rounded-t-${static}',
    'rounded-l-${static}',
    'rounded-r-${static}',
    'rounded-b-${static}',

    'rounded-[11px]',
    'rounded-t-[var(--radius)]',
    'rounded-r-[var(--radius)]',
    'rounded-b-[var(--radius)]',
    'rounded-l-[var(--radius)]',
    'rounded-tr-[var(--radius)]',
    'rounded-br-[var(--radius)]',
    'rounded-bl-[var(--radius)]',
    'rounded-tl-[var(--radius)]',

    'rounded-tl-${static}',
    'rounded-tr-${static}',
    'rounded-br-${static}',
    'rounded-bl-${static}',

    'rounded-${int}xl',
    'rounded-${size}',
    'rounded-t-${int}xl',
    'rounded-t-${size}',
    'rounded-l-${int}xl',
    'rounded-l-${size}',
    'rounded-r-${int}xl',
    'rounded-r-${size}',
    'rounded-b-${int}xl',
    'rounded-b-${size}',
    'rounded-tl-${int}xl',
    'rounded-tl-${size}',
    'rounded-tr-${int}xl',
    'rounded-tr-${size}',
    'rounded-br-${int}xl',
    'rounded-br-${size}',
    'rounded-bl-${int}xl',
    'rounded-bl-${size}',
  ],
  borderWidth: [
    'border-${static}',
    'border-${int}',
    'border-${size}',
    'border-[2.5px]',
    'border-t-${int}',
    'border-t-${size}',
    'border-r-${int}',
    'border-r-${size}',
    'border-b-${int}',
    'border-b-${size}',
    'border-l-${int}',
    'border-l-${size}',
  ],
  boxShadow: [
    'shadow-${static}',
  ],
  boxShadowColor: [
    'shadow-${color}',
  ],
  brightness: [
    'brightness-${static}',
    'brightness-[300%]',
  ],
  caretColor: [
    'caret-${color}',
  ],
  caretOpacity: [
    'caret-opacity-${static}',
  ],
  container: [
    'container',
  ],
  contrast: [
    'contrast-${static}',
    'contrast-[2.4]',
  ],
  cursor: [
    'cursor-${static}',
  ],
  divideColor: [
    'divide-${color}',
  ],
  divideOpacity: [
    'divide-${static}',
    'divide-opacity-${int<=100}',
  ],
  divideWidth: [
    'divide-y-reverse',
    'divide-x-reverse',
    'divide-y-${int}',
    'divide-x-${int}',
  ],
  dropShadow: [
    'drop-shadow-${static}',
  ],
  fill: [
    'fill-${color}',
    'fill-[#1c1c1e]',
    'fill-[var(--color)]',
  ],
  flex: [
    'flex-${static}',
    'flex-[var(--flex)]',
  ],
  flexGrow: [
    'flex-grow-${static}',
    'flex-grow-[var(--grow)]',
  ],
  flexShrink: [
    'flex-shrink-${static}',
    'flex-shrink-[var(--shrink)]',
  ],
  fontFamily: [
    'font-${static}',
  ],
  fontSize: [
    'text-${static}',
    'text-${int}xl',
    'text-[2.23rem]',
  ],
  fontWeight: [
    'font-${static}',
    'font-${int}',
  ],
  gap: [
    'gap-${static}',
    'gap-x-${static}',
    'gap-y-${static}',

    'gap-${float}',
    'gap-x-${float}',
    'gap-y-${float}',

    'gap-${size}',
    'gap-x-${size}',
    'gap-y-${size}',
  ],
  gradientColorStops: [
    'from-${color}',
    'from-[#da5b66]',
    'from-[var(--color)]',
    'via-${color}',
    'via-[#da5b66]',
    'via-[var(--color)]',
    'to-${color}',
    'to-[#da5b66]',
    'to-[var(--color)]',
  ],
  grayscale: [
    'grayscale-${static}',
    'grayscale-[0.55]',
  ],
  gridAutoColumns: [
    'auto-cols-${static}',
  ],
  gridAutoRows: [
    'auto-rows-${static}',
  ],
  gridColumn: [
    'col-${static}',
    'col-span-${int}',
    'col-[7]',
  ],
  gridColumnEnd: [
    'col-end-${static}',
    'col-end-${int}',
    'col-end-[7]',
  ],
  gridColumnStart: [
    'col-start-${static}',
    'col-start-${int}',
    'col-start-[7]',
  ],
  gridRow: [
    'row-${static}',
    'row-span-${int}',
    'row-[7]',
  ],
  gridRowEnd: [
    'row-end-${static}',
    'row-end-${int}',
    'row-end-[7]',
  ],
  gridRowStart: [
    'row-start-${static}',
    'row-start-${int}',
    'row-start-[7]',
  ],
  gridTemplateColumns: [
    'grid-cols-${static}',
    'grid-cols-${int}',
    'grid-cols-[200px,repeat(auto-fill,minmax(15%,100px)),300px]',
  ],
  gridTemplateRows: [
    'grid-rows-${static}',
    'grid-rows-${int}',
    'grid-rows-[200px,repeat(auto-fill,minmax(15%,100px)),300px]',
  ],
  height: [
    'h-${static}',
    'h-${float}',
    'h-${fraction}',
    'h-${int}xl',
    'h-${size}',
    'h-[3.23rem]',
    'h-[calc(100%+1rem)]',
    'h-[var(--width)]',
  ],
  hueRotate: [
    'hue-rotate-${static}',
    'hue-rotate-[0.8turn]',
  ],
  inset: [
    'inset-${static}',
    'inset-${float}',
    'inset-${fraction}',
    'inset-${size}',
    'inset-[11px]',

    'inset-y-${static}',
    'inset-y-${float}',
    'inset-y-${fraction}',
    'inset-y-${size}',

    'inset-x-${static}',
    'inset-x-${float}',
    'inset-x-${fraction}',
    'inset-x-${size}',

    'top-${static}',
    'top-${float}',
    'top-${fraction}',
    'top-${size}',

    'right-${static}',
    'right-${float}',
    'right-${fraction}',
    'right-${size}',

    'bottom-${static}',
    'bottom-${float}',
    'bottom-${fraction}',
    'bottom-${size}',

    'left-${static}',
    'left-${float}',
    'left-${fraction}',
    'left-${size}',
  ],
  invert: [
    'invert-${static}',
    'invert-[0.75]',
  ],
  letterSpacing: [
    'tracking-${static}',
    'tracking-${size}',
    'tracking-[var(--tracking)]',
  ],
  lineHeight: [
    'leading-${static}',
    'leading-${int}',
    'leading-${size}',
    'leading-[var(--leading)]',
  ],
  listStyleType: [
    'list-${static}',
  ],
  margin: [
    'm-${static}',
    'my-${static}',
    'mx-${static}',
    'mt-${static}',
    'mr-${static}',
    'mb-${static}',
    'ml-${static}',

    'm-${float}',
    'my-${float}',
    'mx-${float}',
    'mt-${float}',
    'mr-${float}',
    'mb-${float}',
    'ml-${float}',

    'm-${size}',
    'my-${size}',
    'mx-${size}',
    'mt-${size}',
    'mr-${size}',
    'mb-${size}',
    'ml-${size}',

    'm-[7px]',
    'my-[7px]',
    'mx-[7px]',
    'mt-[7px]',
    'mr-[7px]',
    'mb-[7px]',
    'ml-[7px]',
    'mt-[clamp(30px,100px)]',
  ],
  maxHeight: [
    'max-h-${static}',
    'max-h-${float}',
    'max-h-${fraction}',
    'max-h-${int}xl',
    'max-h-${size}',
  ],
  maxWidth: [
    'max-w-${static}',
    'max-w-${float}',
    'max-w-${fraction}',
    'max-w-${int}xl',
    'max-w-${size}',
    'max-w-[3.23rem]',
    'max-w-[calc(100%+1rem)]',
    'max-w-[var(--width)]',
    'max-h-[3.23rem]',
    'max-h-[calc(100%+1rem)]',
    'max-h-[var(--width)]',
  ],
  minHeight: [
    'min-h-${static}',
    'min-h-${float}',
    'min-h-${fraction}',
    'min-h-${int}xl',
    'min-h-${size}',
    'min-h-[3.23rem]',
    'min-h-[calc(100%+1rem)]',
    'min-h-[var(--width)]',
  ],
  minWidth: [
    'min-w-${static}',
    'min-w-${float}',
    'min-w-${fraction}',
    'min-w-${int}xl',
    'min-w-${size}',
    'min-w-[3.23rem]',
    'min-w-[calc(100%+1rem)]',
    'min-w-[var(--width)]',
  ],
  objectPosition: [
    'object-${static}',
  ],
  opacity: [
    'opacity-${static}',
    'opacity-${int<=100}',
    'opacity-[var(--opacity)]',
  ],
  order: [
    'order-${static}',
    'order-${int}',
  ],
  outline: [
    'outline-${static}',
    'outline-[var(--outline)]',
  ],
  outlineColor: [
    'outline-${color}',
    'outline-solid-${color}',
    'outline-dotted-${color}',
  ],
  padding: [
    'p-${static}',
    'p-[var(--app-padding)]',
    'py-${static}',
    'px-${static}',
    'pt-${static}',
    'pr-${static}',
    'pb-${static}',
    'pl-${static}',

    'p-${float}',
    'py-${float}',
    'px-${float}',
    'pt-${float}',
    'pr-${float}',
    'pb-${float}',
    'pl-${float}',

    'p-${size}',
    'py-${size}',
    'px-${size}',
    'pt-${size}',
    'pr-${size}',
    'pb-${size}',
    'pl-${size}',
  ],
  perspective: [
    'perspect-${static}',
  ],
  perspectiveOrigin: [
    'perspect-origin-${static}',
  ],
  placeholderColor: [
    'placeholder-${color}',
    'placeholder-[var(--placeholder)]',
  ],
  placeholderOpacity: [
    'placeholder-opacity-${static}',
    'placeholder-opacity-${int<=100}',
    'placeholder-opacity-[var(--placeholder)]',
  ],
  ringColor: [
    'ring-${color}',
    'ring-[#76ad65]',
  ],
  ringOffsetColor: [
    'ring-offset-${color}',
    'ring-offset-[#76ad65]',
  ],
  ringOffsetWidth: [
    'ring-offset-${static}',
    'ring-offset-${int}',
    'ring-offset-[10px]',
  ],
  ringOpacity: [
    'ring-${static}',
    'ring-opacity-${int<=100}',
    'ring-opacity-[var(--ring-opacity)]',
  ],
  ringWidth: [
    'ring-${static}',
    'ring-${int}',
    'ring-[10px]',
  ],
  rotate: [
    'rotate-${static}',
    'rotate-x-${static}',
    'rotate-y-${static}',
    'rotate-z-${static}',
    'rotate-${float}',
    'rotate-x-${float}',
    'rotate-y-${float}',
    'rotate-z-${float}',
    'rotate-[23deg]',
    'rotate-[2.3rad]',
    'rotate-[401grad]',
    'rotate-[1.5turn]',
  ],
  saturate: [
    'saturate-${static}',
    'saturate-[180%]',
  ],
  scale: [
    'scale-${static}',
    'scale-${int}',
    'scale-x-${static}',
    'scale-x-${int}',
    'scale-y-${static}',
    'scale-y-${int}',
    'scale-z-${static}',
    'scale-z-${int}',
  ],
  sepia: [
    'sepia-${static}',
    'sepia-[0.2]',
  ],
  skew: [
    'skew-x-${static}',
    'skew-x-${float}',
    'skew-y-${static}',
    'skew-y-${float}',
    'skew-x-[3px]',
    'skew-y-[3px]',
  ],
  space: [
    'space-y-${static}',
    'space-y-reverse',
    'space-x-${static}',
    'space-x-reverse',
    'space-y-${float}',
    'space-x-${float}',
    'space-x-[20cm]',
    'space-x-[calc(20%-1cm)]',
  ],
  stroke: [
    'stroke-${color}',
    'stroke-[#da5b66]',
  ],
  strokeWidth: [
    'stroke-${static}',
    'stroke-${int}',
  ],
  strokeDashArray: [
    'stroke-dash-${static}',
    'stroke-dash-${int}',
  ],
  strokeDashOffset: [
    'stroke-offset-${static}',
    'stroke-offset-${int}',
  ],
  tabSize: [
    'tab-${static}',
  ],
  textColor: [
    'text-${color}',
  ],
  textOpacity: [
    'text-opacity-${static}',
    'text-opacity-${int<=100}',
  ],
  textShadow: [
    'text-shadow-${static}',
  ],
  textDecorationColor: [
    'underline-${color}',
  ],
  textDecorationOpacity: [
    'underline-opacity-${static}',
    'underline-opacity-${int<=100}',
  ],
  textDecorationLength: [
    'underline-${static}',
    'underline-${int}',
    'underline-${size}',
  ],
  textDecorationOffset: [
    'underline-offset-${static}',
    'underline-offset-${int}',
    'underline-offset-${size}',
  ],
  textIndent: [
    'indent-${static}',
    'indent-${size}',
  ],
  textStrokeColor: [
    'text-stroke-${color}',
  ],
  textStrokeWidth: [
    'text-stroke-${static}',
    'text-stroke-${size}',
  ],
  transformOrigin: [
    'origin-${static}',
  ],
  transitionDuration: [
    'duration-${static}',
    'duration-${int}',
    'duration-[2s]',
    'duration-[var(--app-duration)]',
  ],
  transitionDelay: [
    'delay-${static}',
    'delay-${int}',
    'delay-[var(--delay)]',
  ],
  transitionProperty: [
    'transition-${static}',
  ],
  transitionTimingFunction: [
    'ease-${static}',
  ],
  translate: [
    'translate-${static}',
    'translate-x-${static}',
    'translate-y-${static}',
    'translate-z-${static}',
    'translate-x-${float}',
    'translate-x-${fraction}',
    'translate-x-${size}',
    'translate-y-${float}',
    'translate-y-${fraction}',
    'translate-y-${size}',
    'translate-z-${float}',
    'translate-z-${fraction}',
    'translate-z-${size}',
  ],
  width: [
    'w-${static}',
    'w-${float}',
    'w-${fraction}',
    'w-${int}xl',
    'w-${size}',
    'w-[3.23rem]',
    'w-[calc(100%+1rem)]',
    'w-[calc(var(--10-10px,calc(-20px-(-30px--40px)))-50px)]',
    'w-[var(--width)]',
    'w-[var(--width,calc(100%+1rem))]',
    'w-[calc(100%/3-1rem*2)]',
  ],
  zIndex: [
    'z-${static}',
    'z-${int}',
  ],

  // Plugins
  typography: [
    'prose-sm',
    'prose',
    'prose-lg',
    'prose-xl',
    'prose-2xl',
    'prose-red',
    'prose-yellow',
    'prose-green',
    'prose-blue',
    'prose-indigo',
    'prose-purple',
    'prose-pink',
  ],
  aspectRatio: [
    'aspect-none',
    'aspect-w-${float}',
    'aspect-h-${float}',
    'aspect-${fraction}',
  ],
  lineClamp: [
    'line-clamp-none',
    'line-clamp-${int}',
  ],
};

const negative: { [key:string]: true} = {
  inset: true,
  zIndex: true,
  order: true,
  margin: true,
  space: true,
  letterSpacing: true,
  rotate: true,
  translate: true,
  skew: true,
};

export { utilities, negative };
